version: '3.8'

services:
  app:
    # build: .
    image: ghcr.io/betterandbetterii/bb-notify:latest
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./persist:/app/persist
    env_file: .env
